# Generated by Django 3.2.6 on 2021-10-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.TextField()),
                ('result', models.FloatField()),
                ('testId', models.IntegerField()),
            ],
        ),
    ]
